BASE_URL_DEMO="https://kaushal.dord.gov.in/demobackend/ddugkyapp/"
BASE_URL_LIVE="https://kaushal.rural.gov.in/backend/ddugkyapp/"
CLIENT_SECRET_KEY="dgtbncbehkcbjebccnkec78yf37bc"
REFRESH_TOKEN_URL="jhbheugcy2373y379y37gydygdy"
ENCRYPT_KEY = "$10A80$10A80$10A80$10A80$10A80$10A80$10A80$10A80"
ENCRYPT_IV_KEY = "$10A80$10A80$10A80$10A80$10A80$10A80$10A80$10A80"
CRYPLIBAES ="AES/CBC/PKCS5PADDING"
CRYPT_ID =  "AES/CBC/8080808080808080"
CRYPT_IV = "AES/CBC/8080808080808080"
WADH_KEY = "sgydIC09zzy6f8Lb3xaAqzKquKe9lFcNR9uTvYxFp+A="
FACE_AUTH_UIADI="https://nregarep2.nic.in/uid_gramg/stateservices/Uid_Face_Auth_DDUGKY.svc/PostOnAUA_Face_auth"
CAPTURE_INTENT="in.gov.uidai.rdservice.face.CAPTURE"
USER_NAME_FOR_APP= "DDUGKYUSER"

