package com.deendayalproject.model.request

data class insertRfBasicInfoReq(
    val sanctionOrder: String,
    val schemeName: String,
    val trainingCentre: Int,
    val residentialFacilityName: String,
    val residentialType: String,
    val residentialCenterLocation: String,
    val houseNo: String,
    val streetNo1: String,
    val streetNo2: String,
    val landMark: String,
    val stateCode: String,
    val districtCode: String,
    val blockCode: String,
    val gpCode: String,
    val villageCode: String,
    val policeStation: String,
    val pincode: String,
    val mobile: String,
    val residentialFacilityPhoneNo: String,
    val email: String,
    val typeOfArea: String,
    val latitude: String,
    val longitude: String,
    val geoAddress: String,
    val categoryOfTC: String,
    val distBusStand: String,
    val distAutoStand: String,
    val distRailStand: String,
    val distfromTC: String,
    val pickUpDrop: String,
    val wardName: String,
    val wardGender: String,
    val wardEmployeeId: String,
    val wardAddress: String,
    val wardEmail: String,
    val wardMobile: String,
    val empLetterFile: String,
    val policeVerificationFile: String,
    val loginId: String,
    val appVersion: String,
    val imeiNo: String,
    val resFacilityId: Int
)

