package com.deendayalproject.model.request

data class ITLabDetailsRequest(
    val loginId: String,
    val imeiNo: String,
    val appVersion: String,
    val tcId: String,
    val sanctionOrder: String,
//    val roomNo: Int,
    val roomType: String,
    val roomLength: String,
    val roomWidth: String,
    val roomArea: String,
    val roofType: String,
    val roofTypeAttachment: String,
    val falseCeiling: String,
    val falseCeilingAttachment: String,
    val ceilingHeight: String,
    val ceilingHeightAttachment: String,
    val ventilationArea: String,
    val ventilationAreaAttachment: String,
    val soundLevelSpecifications: String,
    val soundLevel: String,
    val soundLevelAttachment: String,
    val centerSoungProofed: String,
    val centerSoungProofedAttachment: String,
    val roomInfoBoard: String,
    val roomInfoBoardAttachment: String,
    val internalSignage: String,
    val internalSignageAttachment: String,
    val audioCamera: String,
    val audioCameraAttachment: String,
    val lanEnabledComputers: String,
    val lanEnabledComputersAttachment: String,
    val internetConnection: String,
    val internetConnectionAttachment: String,
    val typingTuterComputers: String,
    val typingTuterComputersAttachment: String,
    val tablets: String,
    val tabletsAttachment: String,
    val candidatesChair: String,
    val candidatesChairAttachment: String,
    val trainersChair: String,
    val trainersChairAttachment: String,
    val trainersTable: String,
    val trainersTableAttachment: String,
    val lightsAcademic: String,
    val lightsAttachment: String,
    val fansAcademic: String,
    val fansAttachment: String,
    val electricalPowerBackup: String,
    val electricalPowerBackupAttachment: String,
    val roomPhotograph: String,
    val roomPhotographAttachment: String,
    val airConditioningRoom: String,
    val airConditioningRoomAttachment: String,
)

