package com.deendayalproject.model.request

data class OfficeRoomDetailsRequest(
    val loginId: String? ="",
    val imeiNo: String? ="",
    val appVersion:  String? ="",
    val tcId:  String? ="",
    val sanctionOrder:  String? ="",
    val roomType:  String? ="",
    val roomLength:  String? ="",
    val roomWidth:  String? ="",
    val roomArea: String? ="",
    val roomPhotograph:  String? ="",
    val roomPhotographAttachment: String? ="",
    val roofType:  String? ="",
    val roofTypeAttachment:  String? ="",
    val falseCeiling:  String? ="",
    val falseCeilingAttachment:  String? ="",
    val ceilingHeight:  String? ="",
    val ceilingHeightAttachment:  String? ="",
    val storageSecuringDocument:  String? ="",
    val storageSecuringDocumentAttachment:  String? ="",
    val officeTable:  String? ="",
    val officeTableAttachment:  String? ="",
    val officeChair: String? ="",
    val officeChairAttachment:  String? ="",
    val officeComputerTable: String? ="",
    val officeComputerTableAttachment: String? ="",
    val printerScannerAcademic:  String? ="",
    val printerScannerAttachment: String? = null,
    val digitalCameraAcademic: String? ="",
    val digitalCameraAttachment:  String? ="",
    val electricalPowerBackup:  String? ="",
    val electricalPowerBackupAttachment: String? ="",
)

