package com.deendayalproject.model.response

data class ResidentialFacilityQTeam(  val wrappedList: MutableList<FacilityQTeam>,
                                      val responseCode: Int,
                                      val responseDesc: String
)

data class FacilityQTeam(
    val distBusStand: String?,
    val districtCode: String?,
    val blockName: String?,
    val gpName: String?,
    val latitude: String?,
    val wardMobile: String?,
    val wardEmail: String?,
    val villageName: String?,
    val trainingCenterName: String?,
    val trainingCenterId: Int?,
    val policeStation: String?,
    val distRailStand: String?,
    val residentialFacilitiesPhNo: String?,
    val stateName: String?,
    val distFromTc: String?,
    val policeVerfictnImage: String?,
    val houseNo: String?,
    val typeOfArea: String?,
    val landmark: String?,
    val geoAddress: String?,
    val email: String?,
    val longitude: String?,
    val senctionOrder: String?,
    val pincode: String?,
    val categoryOfTc: String?,
    val residentialType: String?,
    val blockCode: String?,
    val residentialFacilityName: String?,
    val districtName: String?,
    val resFacilityId: String?,
    val streetNo2: String?,
    val streetNo1: String?,
    val schemeName: String?,
    val mobile: String?,
    val wardEmpId: String?,
    val empLetterImage: String?,
    val villageCode: String?,
    val wardName: String?,
    val wardgender: String?,
    val residentialCenterLocation: String?,
    val pickUpDrop: String?,
    val stateCode: String?,
    val wardAddress: String?,
    val gpCode: String?,
    val distAutoStand: String?
)

